# DE-Store Docker Compose
# This file includes the main docker-compose configuration from docker/docker-compose.yml
#
# Usage: docker compose -f docker/docker-compose.yml up -d
#
# For convenience, you can also run from this directory:
#   docker compose up -d
#
include:
  - docker/docker-compose.yml
