spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: destore
    password: destore123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: destore
    password: destore123

server:
  port: 8083

rabbitmq:
  exchange:
    low-stock: low_stock_exchange
  queue:
    low-stock: low_stock_queue
  routing-key:
    low-stock: inventory.low_stock

logging:
  level:
    com.destore: DEBUG
